version: "3.9"

services:
  blogo:
    image: pluja/blogo:latest
    container_name: blogo
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./articles:/app/articles
    ports:
      - "127.0.0.1:3000:3000"
