services:
  blogo:
    image: pluja/blogo:latest
    container_name: ExtraMilk
    restart: unless-stopped
    volumes:
      - ./articles:/app/articles
      - ./img:/app/static/img
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      # CONFIG
      BLOGO_TITLE: ExtraMilk!
      BLOGO_DESCRIPTION: A Milky Way Idle blog
      BLOGO_KEYWORDS: milkywayidle,mwi,rpgs
      BLOGO_URL: http://localhost:3000
      #BLOGO_ANALYTICS: '<script defer src="https://my.analytics.site/script.js"></script>'
      TIMEZONE: GMT

      # NOSTR CONFIG
      PUBLISH_TO_NOSTR: false
      #NOSTR_NSEC: ""
      #NOSTR_RELAYS: "wss://nostr-pub.wellorder.net,wss://relay.damus.io,wss://relay.nostr.band"